model_name: gpt2-xl
data_train_path: ../../trainingData/FineTuneSetSummer2022/combined_triplet_train.csv
data_validation_path: ../../trainingData/FineTuneSetSummer2022/combined_triplet_validation.csv
output_data_dir: ../../Output/data
output_model_dir: ../../Output/model/gpt2-xl-combined
hyperparameters:
  find_hyperparams_automatically: false
  num_trials: 10
  fp16: true
  deepspeed: true
  grad_accumulation_steps: 2
  eval_batch_size: 1
  learning_rate: 0.000003
  epochs: 1
  train_batch_size: 1
  seed: 1
  eval_steps: 10
  weight_decay: 0.01
refgen:
  temperature: 0.6
  repetition_penalty: 1.1
  do_sample: true
  top_k: 100
  top_p: 1
