# hf settings
model_name: gpt2-large
data_train_path: /home/ubuntu/transformer-fine-tune/data/instruct-reflections/train-echo.csv
deepspeed_config_path: /home/ubuntu/transformer-fine-tune/configs/ds_config_zero3.json
data_validation_path: /home/ubuntu/transformer-fine-tune/data/instruct-reflections/validation-echo.csv
output_data_dir: /home/ubuntu/transformer-fine-tune/models/gpt2-large-echo
output_model_dir: /home/ubuntu/transformer-fine-tune/models/gpt2-large-echo
output_tokenizer_dir: /home/ubuntu/transformer-fine-tune/models/gpt2-large-echo
logging_dir: /home/ubuntu/transformer-fine-tune/logs/
logging_steps: 10
logging_strategy: steps
evaluation_strategy: steps
eval_steps: 10
eval_batch_size: 1
predict_with_generate: false
eval_accumulation_steps: 100
generation_max_length: 200
compute_metrics: false
save_total_limit: 3
save_steps: 10
use_early_stopping: true
load_best_model_at_end: true  # has to be true alongside early stopping
early_stopping_patience: 2
early_stopping_threshold: 0.06
metric_for_best_model: eval_loss
greater_is_better: false  # we want the lowest possible eval_loss
set_seed: false  # do not set seeds to constant value

# wandb settings
experiment_name: echo
wandb_project_name: gpt2-reflector-echo-sweep
wandb_notes: Complete gpt-2 run (GPT2Large) reflector trained on echo data (alpaca like data), with early stopping and bigger batch size
wandb_tags: GPT2-Large, reflector, instruct, echo

# hyperparameter settings
hyperparameters:
  find_hyperparams_automatically: false
  num_trials: 10
  fp16: true
  bf16: true
  deepspeed: true
  gradient_accumulation_steps: 8
  learning_rate: 0.0003
  epochs: 7
  warmup_steps: 100
  epsilon: 1e-7
  batch_size: 1
  sample_every: 100
  seed: 42
  weight_decay: 0.01

# inference settings
refgen:
  max_length: 300
  temperature: 0.6
  repetition_penalty: 1.1
  do_sample: true
  top_k: 100
  top_p: 1
