model_name: gpt2-xl
pretrained: /
data_train_path: ../data/reflection-triplets/complete_reflection_triplets.csv
data_validation_path: ../data/reflection-triplets/complete_validation_reflection_triplets.csv
output_data_dir: ../models
output_model_dir: ../models

hyperparameters:
  find_hyperparams_automatically: false
  num_trials: 10
  fp16: true
  deepspeed: true
  grad_accumulation_steps: 2
  eval_batch_size: 1
  learning_rate: 0.0003
  epochs: 10
  warmup_steps: 100
  epsilon: 1e-7
  batch_size: 1
  sample_every: 100
  seed: 42
  eval_steps: 10
  weight_decay: 0.01

output_directory: ../../Output/test_results/
refgen:
  temperature: 0.6
  repetition_penalty: 1.1
  do_sample: true
  top_k: 100
  top_p: 1
